### ISSUE TITLE
Can I restrict client to certain directory ?

### ISSUE THREAD

**Issue by jokerElsa** [robert-hh/FTP-Server-for-ESP8266-ESP32-and-PYBD#22]
I want to specify certain directory to clients not the root "/". 
I tried modify  cwd:
```
class FTP_client:
    self.cwd = '/user_dir'
```
It works okay on Windows file Explorer but not well on android clients(it still access the very root "/" dir)
Also failed in modifying method :
`def get_absolute_path(self, cwd, payload):`
or maybe i write it wrong can you show me how to modify this.
Thanks for the time.

**Comment by robert-hh** [comment]
That could get a little bit tricky, since ftp works with full path names. You could try to add a hidden (from ftp) root path, which is inserted before path whenever the code accesses real path names, like in the functions send_file_data(), get_file_data(), send_list data() and eventually make_description(). But the latter may work well with the extended path name.
